name: bball
channels:
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
<<<<<<< HEAD
  - _openmp_mutex=4.5
  - asttokens=2.4.1
  - brotli=1.1.0
  - brotli-bin=1.1.0
  - bzip2=1.0.8
  - ca-certificates=2024.9.24
  - colorama=0.4.6
  - comm=0.2.2
  - contourpy=1.3.0
  - cycler=0.12.1
  - decorator=5.1.1
  - exceptiongroup=1.2.2
  - fonttools=4.54.1
  - freetype=2.12.1
  - glib=2.82.2
  - glib-tools=2.82.2
  - gst-plugins-base=1.24.7
  - gstreamer=1.24.7
  - icu=73.2
  - intel-openmp=2024.2.1
  - ipywidgets=8.1.5
  - jedi=0.19.1
  - jupyterlab_widgets=3.0.13
  - kiwisolver=1.4.7
  - krb5=1.21.3
  - lcms2=2.16
  - lerc=4.0.0
  - libblas=3.9.0
  - libbrotlicommon=1.1.0
  - libbrotlidec=1.1.0
  - libbrotlienc=1.1.0
  - libcblas=3.9.0
  - libclang13=19.1.2
  - libdeflate=1.22
  - libexpat=2.6.2
  - libffi=3.4.4
  - libgcc=14.2.0
  - libglib=2.82.2
  - libgomp=14.2.0
  - libiconv=1.17
  - libintl=0.22.5
  - libintl-devel=0.22.5
  - libjpeg-turbo=3.0.3
  - liblapack=3.9.0
  - libogg=1.3.5
  - libpng=1.6.44
  - libsqlite=3.46.0
  - libtiff=4.7.0
  - libvorbis=1.3.7
  - libwebp-base=1.4.0
  - libwinpthread=12.0.0.r4.gg4f2fc60ca
  - libxcb=1.17.0
  - libzlib=1.3.1
  - matplotlib=3.9.2
  - matplotlib-base=3.9.2
  - matplotlib-inline=0.1.7
  - mkl=2024.2.2
  - munkres=1.1.4
  - openjpeg=2.5.2
  - openssl=3.3.2
  - packaging=24.1
  - parso=0.8.4
  - patsy=0.5.6
  - pcre2=10.44
  - pickleshare=0.7.5
  - pillow=11.0.0
  - pip=24.2
  - ply=3.11
  - pthread-stubs=0.4
  - pure_eval=0.2.3
  - pygments=2.18.0
  - pyparsing=3.2.0
  - pyqt=5.15.10
  - pyqt5-sip=12.13.0
  - python=3.12.5
  - python-dateutil=2.9.0post0
  - python-tzdata=2024.2
  - python_abi=3.12
  - pytz=2024.1
  - qhull=2020.2
  - qt-main=5.15.8
  - scipy=1.14.1
  - seaborn=0.13.2
  - seaborn-base=0.13.2
  - setuptools=72.2.0
  - sip=6.7.12
  - six=1.16.0
  - stack_data=0.6.2
  - statsmodels=0.14.4
  - tbb=2021.8.0
  - tk=8.6.13
  - tomli=2.0.2
  - tornado=6.4.1
  - traitlets=5.14.3
  - typing_extensions=4.12.2
  - ucrt=10.0.22621.0
  - unicodedata2=15.1.0
  - vc=14.40
  - vc14_runtime=14.40.33810
  - vs2015_runtime=14.40.33810
  - wcwidth=0.2.13
  - wheel=0.44.0
  - widgetsnbextension=4.0.13
  - xorg-libxau=1.0.11
  - xorg-libxdmcp=1.1.5
  - xz=5.4.6
  - zstd=1.5.6
  - pip:
    - basketball-reference-web-scraper==4.14.0
    - beautifulsoup4==4.12.3
    - black==24.10.0
    - certifi==2024.7.4
    - charset-normalizer==3.3.2
    - click==8.1.7
    - coverage==7.6.2
    - debugpy==1.8.5
    - executing==2.0.1
    - flake8==7.1.1
    - ghp-import==2.1.0
    - idna==3.8
    - iniconfig==2.0.0
    - ipykernel==6.29.5
    - ipython==8.26.0
    - jinja2==3.1.4
    - joblib==1.4.2
    - jupyter-client==8.6.2
    - jupyter-core==5.7.2
    - lxml==5.3.0
    - markdown==3.7
    - markupsafe==3.0.2
    - mccabe==0.7.0
    - mergedeep==1.3.4
    - mkdocs==1.6.1
    - mkdocs-get-deps==0.2.0
    - mypy-extensions==1.0.0
    - nba-scraper==1.0.10
    - nest-asyncio==1.6.0
    - numpy==2.1.0
    - pandas==2.2.2
    - pathspec==0.12.1
    - platformdirs==4.2.2
    - pluggy==1.5.0
    - prompt-toolkit==3.0.47
    - psutil==6.0.0
    - pycodestyle==2.12.1
    - pyflakes==3.2.0
    - pytest==8.3.3
    - pytest-cov==5.0.0
    - pywin32==306
    - pyyaml==6.0.2
    - pyyaml-env-tag==0.1
    - pyzmq==26.2.0
    - requests==2.32.3
    - scikit-learn==1.5.2
    - soupsieve==2.6
    - stack-data==0.6.3
    - threadpoolctl==3.5.0
    - tqdm==4.66.5
    - tzdata==2024.1
    - urllib3==2.2.2
    - watchdog==6.0.0
prefix: C:\Users\aydin\anaconda3\envs\bball
=======
  - beautifulsoup4
  - ipywidgets
  - matplotlib
  - python=3.12
  - requests
  - seaborn
  - tqdm
  - pytest
  - pytest-cov
  - pip:
    - basketball-reference-web-scraper==4.14.0

prefix: /home/aychid/miniconda3/envs/bball
>>>>>>> 2fdeb27 (chore: update environment to be both linux and windows compatible by removing OS dependencies)
